"""add_notes_table

Revision ID: 060d94ea7c08
Revises: f04c92e7eba5
Create Date: 2026-03-20 18:48:43.356134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060d94ea7c08'
down_revision: Union[str, Sequence[str], None] = 'f04c92e7eba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_ts'), ['ts'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_first_seen'), ['first_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_first_seen'))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_ts'))
        batch_op.drop_index(batch_op.f('ix_notes_entity_type'))
        batch_op.drop_index(batch_op.f('ix_notes_entity_id'))

    op.drop_table('notes')
    # ### end Alembic commands ###
